### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by sybetjeh** [codeuk/WhackDDOS#3]
C:\Users\32493\OneDrive\Desktop\WhackDDOS-main>WhackDDOS.py
  File "C:\Users\32493\OneDrive\Desktop\WhackDDOS-main\WhackDDOS.py", line 34
    async def status_task():
    ^
SyntaxError: invalid syntax

How do you fix that exactly?

**Comment by codeuk** [comment]
line 34 doesn't even have an async call
